Remove -t and -tt functionality from ironpython
IronLanguages/ironpython3 pull request #1131
Opened 2021-03-13 21:44 UTC by dc366

This is a PR for issue #982, which removes console flags for indentation inconsistency. As suggested by @BCSharp, the arguments parser ignores `-t` and `-tt` by taking no action on them.

I have not updated the test suite. I see that the relevant test is `test_t()` in `test_stdconsole.py`. Curiously, the test suite only fails on `net46` after I make these changes.

Your comments are appreciated!

- [x]  Ignore -t and -tt command line arguments
- [x] Remove -t and -tt from command line help
- [x] Remove sys.flags.tabcheck
- [x] Remove PythonOptions.IndentationInconsistencySeverity and related code

2021-03-13 21:45 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/IronLanguages/ironpython3?pullRequest=1131) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/IronLanguages/ironpython3?pullRequest=1131) before we can accept your contribution.<br/><br/>:x: dc366 [sign now](https://cla.dotnetfoundation.org/IronLanguages/ironpython3?pullRequest=1131)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/IronLanguages/ironpython3?pullRequest=1131) it.</sub>

2021-03-13 22:01 UTC, slozier requested changes
Thanks for the PR.

Unfortunately I think you removed some of the wrong code paths. I guess in the description it should have been noted that the expected behavior is what we would have with the `-tt` option turned on. That means we should keep the code that would run with `IndentationInconsistencySeverity == Severity.Error`.

2021-03-13 22:01 UTC, slozier commented on Src/IronPython/Compiler/Tokenizer.cs
> -                return ReadNewlineWithChecks();
I believe `ReadNewlineWithChecks` is what we want to keep.

2021-03-13 22:08 UTC, slozier commented
As for `test_stdconsole` only failing on `net46` it's because the whole suite is disabled in .NET Core.

2021-03-14 00:02 UTC, slozier commented on Src/IronPython/Compiler/Tokenizer.cs
> -                    _state.IndentFormat = new StringBuilder[MaxIndent];
Seeing a bunch of
> SystemError: Object reference not set to an instance of an object

in the CI log. Probably need to move this initialization to the constructor.

2021-03-16 03:11 UTC, dc366 commented
I moved the initialization of indentFormat to the State constructor. In testing on my end, there are a few new test cases which fail as a result of this change. 

I realized I went beyond the scope of the original issue, from simply ignoring the command line flags for indentation warnings to forcing the tokenizer to check for inconsistent indentation (though this is the desired behavior in Python3). I am not sure I have the ability to debug the behavior of the new ReadNewline() function without spending a lot more time. Let me know what you think a reasonable stopping point is.

2021-03-16 14:02 UTC, slozier approved these changes
No problem! This is great (and exactly what I had in mind as resolution of the issue).

Most of the test failures were expected with this change and I amended the tests to pass. It looks like there was one bug in the original `ReadNewlineWithChecks` which I fixed.

2021-03-16 16:34 UTC, merged

2021-03-16 16:35 UTC, slozier commented
Thanks for the PR!